services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-wish-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
    networks:
      - car-wish-network
    depends_on:
      - database
  database:
    image: postgres:16-alpine
    container_name: car-wish-db-app
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - car-wish-network
  minio:
    image: minio/minio:latest
    container_name: car-wish-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - car-wish-network

networks:
  car-wish-network:
    name: car-wish-network
