services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-wish-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
    networks:
      - car-wish-network
    depends_on:
      - database
  database:
    image: postgres:16-alpine
    container_name: car-wish-db-app
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - car-wish-network

networks:
  car-wish-network:
    name: car-wish-network
